# auto start
exec --no-startup-id nm-applet
exec_always --no-startup-id ~/.config/polybar/polybar-i3.sh
exec_always --no-startup-id picom --config ~/.config/picom/picom.conf -b
exec_always --no-startup-id dunst
