# rofi
bindsym $alt+space exec rofi -show drun --replace -i
bindsym $alt+Tab exec rofi -show window --replace -config ~/.config/rofi/window.rasi -i
bindsym $alt+r exec rofi -show run --replace -config ~/.config/rofi/run.rasi -i
bindsym $alt+p exec rofi -show power-menu -modi power-menu:~/.config/rofi/rofi-power-menu -i

# which poweroff
bindsym $mod+Shift+u exec systemctl poweroff

# i3 reload restart quit
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -B 'Yes, exit i3' 'i3-msg exit'"

# kill focus window
bindsym $mod+q kill

# browser
bindsym $mod+b exec firefox

# terminal
bindsym $mod+Return exec wezterm

# file explorer
bindsym $mod+e exec thunar

# focus window
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right

# move window
bindsym $mod+Shift+h move left
bindsym $move+Shift+j move down
bindsym $move+Shift+k move up
bindsym $move+Shift+l move right

# toggle split dimension
bindsym $mod+a split h
bindsym $mod+d split v

# window action
bindsym $mod+f fullscreen toggle
bindsym $mod+p layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+z layout toggle split
bindsym $mod+t floating toggle
bindsym $mod+n focus mode_toggle
