# rofi
bindsym $alt+space exec rofi -show drun --replace -i
bindsym $alt+Tab exec rofi -show window --replace -config ~/.config/rofi/window.rasi -i
bindsym $alt+r exec rofi -show run --replace -config ~/.config/rofi/run.rasi -i
bindsym $alt+p exec rofi -show power-menu -modi power-menu:~/.config/rofi/rofi-power-menu -i

# which poweroff
bindsym $mod+Shift+u exec systemctl poweroff

# sway reload restart quit
bindsym $mod+Shift+c reload
bindsym $mod+Shift+r restart
bindsym $mod+Shift+e exec swaynag -t warning -m 'You pressed the exit shortcut. Do you really want to exit sway? This will end your Wayland session.' -B 'Yes, exit sway' 'swaymsg exit'

# kill focus window
bindsym $mod+q kill

# browser
bindsym $mod+b exec firefox

# terminal
# bindsym $mod+Return exec wezterm
bindsym $mod+Return exec ghostty

# file explorer
bindsym $mod+e exec thunar

# focus window
bindsym $mod+h focus left
bindsym $mod+j focus down
bindsym $mod+k focus up
bindsym $mod+l focus right
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move window
bindsym $mod+Shift+h move left
bindsym $mod+Shift+j move down
bindsym $mod+Shift+k move up
bindsym $mod+Shift+l move right
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# toggle split dimension
bindsym $mod+a split h
bindsym $mod+d split v

# window action
bindsym $mod+f fullscreen toggle
bindsym $mod+p layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+z layout toggle split
bindsym $mod+t floating toggle
bindsym $mod+n focus mode_toggle

# workspace action
bindsym $mod+ampersand  workspace number 1
bindsym $mod+eacute     workspace number 2
bindsym $mod+quotedbl   workspace number 3
bindsym $mod+apostrophe workspace number 4
bindsym $mod+parenleft  workspace number 5
bindsym $mod+minus      workspace number 6
bindsym $mod+egrave     workspace number 7
bindsym $mod+underscore workspace number 8
bindsym $mod+ccedilla   workspace number 9
bindsym $mod+agrave     workspace number 10
bindsym $alt+ampersand  move container to workspace 1;workspace 1;focus
bindsym $alt+eacute     move container to workspace 2;workspace 2;focus
bindsym $alt+quotedbl   move container to workspace 3;workspace 3;focus
bindsym $alt+apostrophe move container to workspace 4;workspace 4;focus
bindsym $alt+parenleft  move container to workspace 5;workspace 5;focus
bindsym $alt+minus      move container to workspace 6;workspace 6;focus
bindsym $alt+egrave     move container to workspace 7;workspace 7;focus
bindsym $alt+underscore move container to workspace 8;workspace 8;focus
bindsym $alt+ccedilla   move container to workspace 9;workspace 9;focus
bindsym $alt+agrave     move container to workspace 10;workspace 10;focus

# Screenshots
bindsym Print exec --no-startup-id ~/.config/i3/scripts/screenshot.sh
bindsym $mod+Print exec --no-startup-id ~/.config/i3/scripts/screenshot.sh --window
bindsym Shift+Print exec --no-startup-id ~/.config/i3/scripts/screenshot.sh --select
# Clipboard Screenshots
bindsym Ctrl+Print exec --no-startup-id maim | xclip -selection clipboard -t image/png
bindsym Ctrl+$mod+Print exec --no-startup-id maim --window $(xdotool getactivewindow) | xclip -selection clipboard -t image/png
bindsym Ctrl+Shift+Print exec --no-startup-id maim --select | xclip -selection clipboard -t image/png

bindsym F12 input type:keyboard xkb_switch_layout next
